# Generated by Django 4.2.23 on 2025-06-27 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('dream_id', models.AutoField(primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('reformed_prompt', models.TextField()),
                ('transcription', models.TextField()),
                ('img_b64', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends_only', 'Friends only')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dreams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
