# Generated by Django 5.2.3 on 2025-06-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('dream_id', models.AutoField(primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('reformed_prompt', models.TextField()),
                ('transcription', models.TextField()),
                ('img_id', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends_only', 'Friends only')], max_length=20)),
            ],
        ),
    ]
