# Generated by Django 5.2.3 on 2025-06-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='img_id',
        ),
        migrations.AddField(
            model_name='dream',
            name='img_b64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
