# Generated by Django 5.2.6 on 2025-09-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='emotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dream',
            name='emotion_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dream',
            name='emotion_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dream',
            name='emotion_emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
