# Generated by Django 5.2.6 on 2025-09-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0002_dream_emotion_dream_emotion_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends_only', 'Friends only')], default='private', max_length=20),
        ),
    ]
