# Generated by Django 5.2.6 on 2025-09-21 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0007_make_datetime_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dream',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rêve', 'verbose_name_plural': 'Rêves'},
        ),
        migrations.AlterField(
            model_name='dream',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='img_b64',
            field=models.TextField(blank=True, help_text='Image générée du rêve en format base64', null=True, verbose_name='Image en base64'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Privé'), ('friends_only', 'Amis seulement')], default='private', max_length=20, verbose_name='Niveau de confidentialité'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='prompt',
            field=models.TextField(blank=True, help_text='Champ legacy - sera supprimé', null=True, verbose_name='Prompt original (legacy)'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dreams', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='dream',
            index=models.Index(fields=['-created_at'], name='dreams_drea_created_6d1501_idx'),
        ),
        migrations.AddIndex(
            model_name='dream',
            index=models.Index(fields=['user', '-created_at'], name='dreams_drea_user_id_837c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='dream',
            index=models.Index(fields=['privacy', '-created_at'], name='dreams_drea_privacy_8ff4b7_idx'),
        ),
        migrations.AddIndex(
            model_name='dream',
            index=models.Index(fields=['emotion'], name='dreams_drea_emotion_479b76_idx'),
        ),
    ]
