# Generated by Django 5.2.3 on 2025-06-24 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('raw_prompt', models.TextField(verbose_name='Description du rêve (texte brut)')),
                ('image_path', models.URLField(blank=True, max_length=500, null=True, verbose_name="URL de l'image générée")),
                ('emotion_analysis', models.JSONField(blank=True, null=True, verbose_name='Analyse émotionnelle (JSON)')),
                ('visibility', models.CharField(choices=[('private', 'Privé'), ('friends', 'Amis uniquement'), ('public', 'Public')], default='private', max_length=10, verbose_name='Visibilité')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dreams', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Rêve',
                'verbose_name_plural': 'Rêves',
                'ordering': ['-timestamp'],
            },
        ),
    ]
