# Generated by Django 5.2.3 on 2025-06-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='emotion_analysis',
            field=models.TextField(blank=True, null=True, verbose_name='Analyse émotionnelle (JSON)'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Chemin de l'image générée"),
        ),
        migrations.AlterField(
            model_name='dream',
            name='raw_prompt',
            field=models.TextField(verbose_name='Description du rêve brut'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
    ]
