# Generated by Django 5.2.3 on 2025-06-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0002_alter_dream_emotion_analysis_alter_dream_image_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='emotion_analysis',
            field=models.JSONField(blank=True, null=True, verbose_name='Analyse émotionnelle (JSON)'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='image_path',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="URL de l'image générée"),
        ),
        migrations.AlterField(
            model_name='dream',
            name='raw_prompt',
            field=models.TextField(verbose_name='Description du rêve (texte brut)'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement"),
        ),
    ]
